### ISSUE TITLE
submit for Codreview

### ISSUE THREAD

**Issue by sediqullahbadakhsh** [sediqullahbadakhsh/js-group-capstone#21]
Dear Reviewer,

We have copied the template and removed all the tasks belong to student C, and we have decide to who is going to be student A and who is going to be student B.
Here is a link of the project:
[Github project link](https://github.com/sediqullahbadakhsh/js-group-capstone/projects/1)
We are a group of 2, (A team with 2 members)

Regards

**Comment by ShoiraTa** [comment]
### **STATUS: APPROVED  ✔️** 
------
Hi team,  

Your project is complete! Great job for nailing it right on the first attempt 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 



![giphy](https://user-images.githubusercontent.com/77038610/154916093-53a75ff8-ba21-44ad-a25e-bdea6200d8f1.gif)

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
